@Inventory.Api_HostAddress = http://localhost:5258

GET {{Inventory.Api_HostAddress}}/health
Accept: application/json

###

GET {{Inventory.Api_HostAddress}}/api/products
Accept: application/json

###

GET {{Inventory.Api_HostAddress}}/api/inventory
Accept: application/json

###

GET {{Inventory.Api_HostAddress}}/api/kpis
Accept: application/json

###

POST {{Inventory.Api_HostAddress}}/api/import/run
Accept: application/json

###
